### ISSUE TITLE
add reorder_dimensions method to BinnedTensorTransform object

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#104]
Akin to what was added to Map, MapSet, and MultiDimBinning; however, this is more complicated since the shape of the transform can be different from the specified input binning (and the exact behavior of the transform depends upon the shape). So this is somewhat of a stretch goal, but would be handy for people to use.

**Comment by LeanderFischer** [comment]
I don't even know what `BinnedTensorTransform` is, does it still exist? Couldn't find it in the codebase :shrug: I guess we can close this.
