### ISSUE TITLE
propagate invalidated (masked) transform entries to bins

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#106]
Simply masking the transform causes bug since the input map's contents simply get propagated to the output (like multiplying by one). need to figure out a way to propagate masked entries in a transform to the appropriate location(s) in the output map.

Note that this arose in connection with the PID stage, though it could be an issue elsewhere, so a fix of some form within BinnedTensorTransform might make more sense than just in the PID stage itself.

**Comment by LeanderFischer** [comment]
I don't think this is an issue anymore, closing it.
