### ISSUE TITLE
make highly-analysis-specific code e.g. a submodule (separate repos); data files downloaded separately

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#115]
## The problem

We want for PISA itself to be well coded, well tested, well documented, stable, and naturally shared by many analyses.

_However,_ analyzers need to write ad-hoc scripts to do ad-hoc plots and highly specific things to their analyses... and check these in _before_ they are well coded, well tested, well documented, and/or shareable with others.

If we force the first perspective, analyzers will do the easiest thing: fork PISA and use the second perspective for their own analyses in their own branches. These will all diverge, the core PISA tools will be in various states for everyone, and it will again be difficult for improvements to analyses to be shared among all.

If we allow everyone to commit to the PISA master branch whenever they like, the master branch will be total bedlam.
## What to do?

So there needs to be some firewall between PISA and the analyses that use PISA. The way I envision this is there being separate repositories (submodules?) that a user can check out that populate specific directories within PISA with their analysis-specific configuration files, scripts, etc.

These should also be isolated into apprpriately named directories. e.g., the `psu_nutau` directories in `$PISA/pisa/resources/settings/pipeline_settings/psu_nutau` and `$PISA/analysis_scripts/psu_nutau` would be created and populated when a user checks out some `WIPACrepo/pisa-psu_nutau` sub-module / github repo (or something like this, I'm not sure about the technical details).
## What about data files?

The other piece is handling data files, which really shouldn't be managed by git in the first place (these make repo's huge and unwieldy; git is designed for source code, _not_ data). So it'd be nice to have data files download. Also, since data files can be shared among analyses, it might be useful to be able to download files to a shared directory, maybe in addition to the analysis-specific directories.

**Comment by LeanderFischer** [comment]
Not that the solution of outsourcing analysis code to the fridge is great, but it works, so I'm closing this as _solved_.
