### ISSUE TITLE
param_selector mechanism is crude and undocumented

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#120]
How to "throw the switch" between param_selector values is crude at best at the moment; this must be done on the output of the Python `ConfigParser` module but prior to that being parsed by the `config_parser.py`/`parse_pipeline_config`.

TODO's:
- Current mechanism needs to be documented, preferably with example(s) (for Milestone 3.0.0)
- New mechanism devised that can operate directly within an instantiated pipeline so such a hack isn't necessary to achieve the purpose (for Milestone 3.1)

**Comment by LeanderFischer** [comment]
Calling `param_selections` works for me, I don't think this issue persists, closing it.
