### ISSUE TITLE
pisa name exists in PyPI

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#126]
Can cause confusion, installation issues; the description certainly isn't confusing, but how to proceed may be. Can we come up with a different package name that gets referenced in the pip database? I have no idea how this works...

``` bash
$ pip search pisa
pisa (3.0.33)                                  - PDF generator using HTML and CSS
```

**Comment by LeanderFischer** [comment]
The problem is being tackled via https://github.com/pypi/support/issues/2813.

**Comment by LeanderFischer** [comment]
Wow, this issue is from 2016 omg.

**Comment by LeanderFischer** [comment]
Moved into [active processing a few weeks ago](https://github.com/pypi/support/issues/2813) :tada:

**Comment by LeanderFischer** [comment]
Closing since https://github.com/pypi/support/issues/2813 is successfully completed now.
