### ISSUE TITLE
Package PISA for easy install/run in remote environments (e.g. OSG)

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#134]
Related to issues #115 and #124 and #125. Note that having so much data included is detrimental; a download script for only the needed data files is probably a good idea. (This should include the test data, too, I think such that installs can be as fast as possible in cluster environments, where having test data on every install is irrelevant once the cluster has had tests run once.)

Tools for doing this include e.g. http://www.pyinstaller.org.

**Comment by LeanderFischer** [comment]
Hm, I don't know if people are running fits on the OSG, but I haven't heard anyone complain about the install being to big, so I close this now.
