### ISSUE TITLE
FTYPE definition in one place across all code; respected by all code

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#184]
* ☑ FTYPE defined in `const.py`
* ☑ Picks up and uses env var  `PISA_FTYPE` if it's defined 
* ☑ This is imported in `$PISA/pisa/__init__.py`, so users can do `from pisa import FTYPE`
* ☑ Convert mosc.cu and mosc3.cu to use this
* ☐ Use this dynamically in Prob3++

**Comment by LeanderFischer** [comment]
I feel like this is now also used properly in prob3, closing it.
