### ISSUE TITLE
VBW-KDE able to utilize Sebastian Schoenen's KDE module

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#203]
Be able to use either the current implementation (Improved Sheather Jones pilot density estimate + Abramov bandwidth selection) or something from Sebastian Schoenen's KDE module.

**Comment by LeanderFischer** [comment]
Ok, yes, that looks cool, but we've been doing very well without, so closing this..

**Comment by LeanderFischer** [comment]
Does anyone even use `vbwkde`? I don't think this is needed, closing it..
