### ISSUE TITLE
Errors running in single precision mode with non-Asimov datasets

### ISSUE THREAD

**Issue by steven-j-wren** [icecube/pisa#229]
Running `hypo_testing.py` for NMO studies and getting errors with parameters going to NaN when running in single precision. I modified the error message so it would tell me which parameter and it seems it's happening with the muon background:
```
ValueError: Param atm_muon_scale has a value nan dimensionless which is not in the range of (<Quantity(0.01, 'dimensionless')>, <Quantity(1.0, 'dimensionless')>)
```
This could be a problem with non-Asimov datasets or, given that it's in the muon background, it could be something in the `icc` script. I set off 4 jobs in single precision, each to run 50 trials, and they all failed after some number of trials (< 10, but I think that's fairly irrelevant). All trials done in double precision are finishing fine.

**Comment by LeanderFischer** [comment]
I can't see whether this issue persists.

**Comment by thehrh** [comment]
Let's close as "not planned" because there is no way to reproduce the original issue with the execution of `hypo_testing.py`. There doesn't seem to be anything we can do about the possible external minimiser issue raised above (apart from reintroducing a user documentation somewhere).
