### ISSUE TITLE
How should equality for a Map behave?

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#235]
What I have implemented now I always knew might be problematic, so this is a TODO from the code that should be discussed among the group, and particularly after several users have now had some time using PISA 3.

See the `__eq__` method of `Map` for current implementation of the logic:
https://github.com/jllanfranchi/pisa/blob/cake/pisa/core/map.py#L1227

**Comment by LeanderFischer** [comment]
Current implementation seems ok for what people need, closing.
