### ISSUE TITLE
`DistributionMaker.get_outputs(return_sum=True)`: first Map name is used (others discarded)

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#246]
First Map name is kept (others discarded) `DistributionMaker.get_outputs(return_sum=True)`. (My first thoughts are that this bug may be in `DistributionMaker` but also might be in `Map` and/or `MapSet`.)

Options:
1. rename result e.g. `' + '.join([m.name for m in maps])`
  * Pretty and informative
  * Potentially unwieldy names (long, non-python-friendly characters plus and space)
  * Difficult to work with: maps in MapSets are synced by name; cannot use dotted notation, and string access becomes more and more difficult
  * Alternative to this would be to create a _new_ field in the `Map` object that captures such info (and/or tex version thereof) that can be carried along with the `Map` but not affect how you work with the `Map` 
2. rename result `'total'`
  * Simple
  * Allows one summed result to be compared against another without having to rename things first
  * Solution that @steven-j-wren is using (he found this issue and needed some solution like this to make `make_akhmedov_plots.py` work)

**Comment by LeanderFischer** [comment]
Has been working fine, so I'm closing it.

**Comment by JanWeldert** [comment]
Option 2 has been implemented.
