### ISSUE TITLE
Installation of llvmlite package (required by numba) fails without anaconda distro

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#259]
I thought I had this working previously, but now I cannot seem to get `numba` to install since `llvmlite` is itself failing to install. Looks like same issue as here: https://github.com/numba/llvmlite/issues/182 . Possible I'm missing something, so if someone else can install `numba` (and hence `llvmlite`) _without_ the Anaconda Python distribution, I'd like to hear how you get this working (and what OS / versions of gcc, llvm, etc you have.)

To be clear, `numba` is installable just fine for me using the Anaconda Python distribution (I'm running Ubuntu 16.04).

**Comment by LeanderFischer** [comment]
Nobody else seemed to have complained, so out you go..
