### ISSUE TITLE
Vacuum oscillations should not require PREM_12layer.dat file

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#297]
This has hooks all the way down into c++ code where the earth model is carried around everywhere, even if vacuum oscillations are being used. Some options would be to programatically "create" a file (use e.g. `tempfile` module, and create a dummy earth model file there) or to actually fix the C++ code so it isn't so bad. (Preferable to pull as much into Python, cython, and/or numba.)

**Comment by LeanderFischer** [comment]
I don't think anyone really cares about this anymore -> closing it.
