### ISSUE TITLE
minimizer_settings OrderedDict or otherwise hash "correctly"

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#330]
follow / reformat to follow specific ordering, so that hashing comes out same for equivalent settings. Also  since settings are different for different FTYPE by default, the full settings file will differ for those cases. In other words, a final, normalized, full minimzer settings state--_not_ the actual object passed in--should be hashed on (just as we do for most other objects now in PISA).

**Comment by LeanderFischer** [comment]
This ain't an issue with how we treat `minimizer_settings` right now, right @atrettin

**Comment by atrettin** [comment]
I'm not sure I entirely understand the issue, but since 2017 all of this has dramatically changed and I don't think we need this issue anymore.

**Comment by LeanderFischer** [comment]
Goodbye then :+1:
