### ISSUE TITLE
Record _full_ minimizer settings, not just those set by user

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#366]
Currently only settings changed from defaults are recorded when analysis is run. The full settings should be stored, though, including implicit defaults, just in case those change in the code at some point. (That's part of the reason to make the defaults explicit in `analysis.py`, so that even if Scipy changes its defaults, we know what was used for a given analysis.)

**Comment by LeanderFischer** [comment]
I think this is also not an issue anymore.. (right @atrettin?)

**Comment by atrettin** [comment]
yeah, this is outdated
