### ISSUE TITLE
MCEq doesn't have Honda systematics

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#400]
See comment from @steven-j-wren here: https://github.com/jllanfranchi/pisa/pull/394#issuecomment-335250536

In summary:
"standard `honda.py` systematics should be included in `mceq.py`. I think this could be as simple as importing them from `honda.py` but I'm not sure exactly what set of maps is output by `mceq.py`"

**Comment by LeanderFischer** [comment]
Honda systematics? Nononono :no_bell:
