### ISSUE TITLE
pisa/__init__.py `cuda.close()` call might interfere with other code

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#403]
Not sure about this one, just something to check / verify it doesn't affect other code that has already initialized cuda (numba cuda at least, probably no affect on pycuda).

**Comment by LeanderFischer** [comment]
[Those lines](https://github.com/icecube/pisa/blob/master/pisa/__init__.py#L145-L146) are effectively commented out, so it does not matter..
