### ISSUE TITLE
hypo_testing.py doesn't work with osc.prob3gpu and reco.vbwkde

### ISSUE THREAD

**Issue by JanWeldert** [icecube/pisa#417]
Using the hypo_testing.py script with a pipeline containing osc.prob3gpu and reco.vbwkde delivers the following error:

pycuda._driver.LogicError: cuFuncSetBlockShape failed: invalid resource handle

This problem is probably related to https://github.com/WIPACrepo/pisa/blob/cake_pre_opensource/pisa/utils/gaussians.py :

```
# TODO: if the Numba CUDA functions are defined, then other CUDA (e.g. pycuda)
# code doesn't run (possibly only when Nvidia driver is set to
# process-exclusive or thread-exclusive mode). Need to fix this behavior. (E.g.
# context that gets destroyed?)
```

**Comment by LeanderFischer** [comment]
Does this still pose an issue @JanWeldert, otherwise feel free to get rid of this issue, please :pray:
