### ISSUE TITLE
Github Markdown Format (GMF) tables don't render in compiled docs

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#425]
This was disappointing to discover. Still desirable in my mind to make github repo directly useful for documentation and browsing files, so I don't like the idea of messing up formatting there. The compiled docs might be less important in this case... depending on your perspective, and where people are _actually_ reading the docs (if they read the docs at all).

There are issues open for this in recommonmark starting from July 2015 (https://github.com/rtfd/recommonmark/issues/3), but nothing has been done. So if we want this kind of support, either we build it ourselves (no way), find a workaround, or accept some ugly-looking compiled docs.

**Comment by LeanderFischer** [comment]
Support is there now, don't think this is still an issue..
