### ISSUE TITLE
Redirect output of MCEq, nuSQuiDS to logging

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#429]
stdout (and/or stderr) messages from MCEq, nuSQuiDS clutter PISA's output and are not going into logging module, and hence possible useful debug messages will be lost by people using the logging module (plus they can't be turned off, so clutter is unavoidable at present).

So:
* Figure out how to redirect to logging
* Set messages from as debug level messages?

**Comment by LeanderFischer** [comment]
Wasn't a problem in 7 years, so bye..
