### ISSUE TITLE
`root_numpy` dependency not documented, not easy to install

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#431]
Also, apparently specific version(s) of ROOT and/or numpy might be required to get `root_numpy` to install. Please add info on which version(s) are "legal" to `INSTALL.md` and make some note of the dependency in the `rooutils.py` file EDIT: also in `stages/unfold/roounfold.py`). (I tried a quick `pip install root_numpy` and it failed asking for ROOTSYS, so if there is also a recipe for installing this, that'd be helpful.)

**Comment by LeanderFischer** [comment]
Also `rooutils.py` is gone, right, so closable, too..
