### ISSUE TITLE
Undocumented dependencies in `stages.unfold.roounfold`

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#432]
Fails at
```python
from ROOT import RooUnfoldResponse, RooUnfoldBayes
```

Add info to `INSTALL.md` about optional dependencies (and which version(s) are required); add note in `roounfold.py` about the dependencies. Include any install recipe / help if it's tricky to install, too.

**Comment by LeanderFischer** [comment]
I don't think `stages.unfold.roounfold` exists anymore, so close, yes?
