### ISSUE TITLE
Auto documentation generation

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#54]
Create a script that checks the `master` branch for updated version, and when this is seen, the script rebuilds the documentation and uploads it to whatever web server we're using for hosting the Sphinx-generated docs. (Alternatively, the script can be running on that server so the upload isn't necessary, just needs to copy things to the correct directory.)

**Comment by LeanderFischer** [comment]
Automatically creating documentation with every PR could potentially be implemented likes this, if you want to trust the bot: https://chat.openai.com/share/9c9bdec2-3c94-47b1-9233-32c3da3fa31d
I assume this will need some testing to get it running.
