### ISSUE TITLE
Function called by minimizer is ignoring user-defined prior penalty function

### ISSUE THREAD

**Issue by thehrh** [icecube/pisa#572]
* Compare https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/analysis/analysis.py#L1037 to https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/analysis/analysis.py#L849

**Comment by jllanfranchi** [comment]
Looks like this came from @ts4051 and @philippeller here: https://github.com/IceCubeOpenSource/pisa/blame/master/pisa/analysis/analysis.py#L338

**Comment by thehrh** [comment]
The option is uncommented in https://github.com/IceCubeOpenSource/fridge/blob/master/analysis/common/analysis/core/oscillations_analysis.py#L816, though I don't know where else it could have been used

**Comment by thehrh** [comment]
I believe this has been solved by now, as evidenced by https://github.com/icecube/pisa/blob/master/pisa/analysis/analysis.py#L2667.
