### ISSUE TITLE
Hypothesis testing not consistently implemented for "Multidetector" analysis?

### ISSUE THREAD

**Issue by thehrh** [icecube/pisa#584]
Look at how we produce pseudodata by looping over the sequence of asimov distributions for each experiment/detector, https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/analysis/hypo_testing.py#L739, vs. how we don't for pseudodata of the "fiducial" hypothesis: https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/analysis/hypo_testing.py#L900 and https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/analysis/hypo_testing.py#L908.

Hard for me to believe this works. Has this been tested? I would have expected the change to have been part of https://github.com/IceCubeOpenSource/pisa/pull/505 @JanWeldert

**Comment by thehrh** [comment]
I'm reworking things as a part of my upcoming PR and would be grateful for some input here.

**Comment by JanWeldert** [comment]
You'r right, the code in L900 and L908 should be similar to L739

**Comment by thehrh** [comment]
* https://github.com/IceCubeOpenSource/pisa/pull/587/commits/b6eb55c0f9f5b6815a7a160381916796a0977a73#diff-c7850b5e371d92ed3d8a912af9635d77R1200
* https://github.com/IceCubeOpenSource/pisa/pull/587/commits/b6eb55c0f9f5b6815a7a160381916796a0977a73#diff-c7850b5e371d92ed3d8a912af9635d77R1219

**Comment by thehrh** [comment]
Closing because `hypo_testing.py` script with its pseudodata generation for the "fiducial" hypothesis doesn't exist any longer.
