### ISSUE TITLE
Modules fail to import when using gpu (CUDA) mode

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#596]
- [ ] `pisa.stages.flux.pi_mceq_barr`; authors listed: @ts4051 @philippeller @blotsd 
- [x] `pisa.stages.absorption.pi_earth_absorption` no authors; initial commit @atrettin
  - Fixed with with PR #605 / https://github.com/IceCubeOpenSource/pisa/commit/d6d787c3946a5be6e6226c40dd43d149d717ae24

**Comment by philippeller** [comment]
as for pisa4, we will not support cuds in this stage anymore
