### ISSUE TITLE
Generic optimizer to handle different/hybrid parameter optimization techniques

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#60]
Not all free parameters need to be optimized using a "minimizer" as we have envisioned it (something achievable with a simple call to [`scipy.optimize.minimze()`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize)). For example, some free parameters could be optimized quickly and accurately using the Fisher method or by simply scanning over several values.

Furthermore, if different parameters are optimized with different techniques (or using the same technique but with different settings), the minimization over _all_ parameters must be handled carefully. I'll term this __hybrid__ optimization when different techniques and/or settings are used to optimize different subsets of the free param values.

E.g., for __hybrid__ optimization, with techniques/settings (1) through (N), I think we would need to optimize with all parameters that make use of technique/settings (1), then those that make use of technique/settings (2), and so on through to parameters that make use of technique/settings (N). Then we have to re-start at technique/settings (1) and go through (N) again, until some `max_supersteps` is exceeded or a full pass from (1) to (N) changes the metric by less than `tol_supersteps` tolerance in the match metric. 

To implement "non-standard" optimization, we have a couple of options that I can think of right now:
1. Make a callable that is passable to `scipy.oiptimize.minimize()` via its `method` argument (which otherwise takes strings to denote the "standard" minimizer methods already implemented within Scipy). For simplicity for now, say that this callable will just handle the non-standard optimization technique(s) individually (and not handle what I've termed "hybrid" optimization).
2. Make a more generic `Optimizer` interface/object that can handle non-standard optimization techniques.
3. Use 1. above for non-standard techniques, and make the `Optimizer` object in 2. instead to understand how to deal with hybrid optimization--as well as the simple sub-case of that, where there's a single optimization technique used to optimize all parameters.

**Comment by atrettin** [comment]
I guess this has ultimately been addressed with the recursive optimization strategies that are now in PISA.
