### ISSUE TITLE
The next numba headache

### ISSUE THREAD

**Issue by philippeller** [icecube/pisa#662]
NumbaDeprecationWarning: The 'target' keyword argument is deprecated

**Comment by thehrh** [comment]
This seems to refer to https://numba.readthedocs.io/en/0.52.0/reference/deprecation.html#deprecation-of-the-target-kwarg, which claims removal of `target` kwarg from `@numba.jit` in 0.54.0 (pisa requires >=0.53.0). 

Concerning the `target` kwarg in `vectorize` and `guvectorize`, it is still there in the current stable release and is not deprecated either (https://numba.readthedocs.io/en/stable/reference/jit-compilation.html, https://numba.readthedocs.io/en/stable/reference/deprecation.html).

https://github.com/icecube/pisa/blob/master/pisa/utils/numba_tools.py#L107, and here in particular https://github.com/icecube/pisa/blob/master/pisa/utils/numba_tools.py#L139, seems fine. I also can't find any use of `jit` throughout the code.

Can this issue thus be closed?

**Comment by thehrh** [comment]
Closing because this doesn't appear to be an issue after all (according to my research above).
