### ISSUE TITLE
Plotting confidence contours

### ISSUE THREAD

**Issue by rruizdeaustri** [icecube/pisa#714]
Hi,

Is there anyway to plot CL contours of the parameters of interest with pisa  ?

Thanks,
Roberto

**Comment by philippeller** [comment]
depends on what you want to do? If you want those over a profiled LLH, then you need to run a grid scan of points, and each point will be a minimization task....

I think some people have made automated scripts to perform such tasks.

**Comment by rruizdeaustri** [comment]
Ok thanks !!
