### ISSUE TITLE
Trying to reproduce pisa results

### ISSUE THREAD

**Issue by rruizdeaustri** [icecube/pisa#724]
Hi,

 I have tried to reproduce pisa results with my own code using vanilla prob3++ and just including detector systematics. I attach the 90% CL contours.

After inspecting the spectra for a few benchmarks I see that it agrees quite well (order 1%) excepting in low energy bins with large zenit angles in which can differ up 5%. If I use squids (matter effects for neutrinos passing through the core of 
Earth) instead of prob3++  the errors in those bins are reduced. So my bet is that a non proper propagation of neutrinos crossing the center of Earth is responsable of the shift in the contours. Does this make sense ? 

On the other hand, what I don't understand is why pisa results differ  with the ones in "Measurement of Atmospheric Neutrino Oscillations at 6-56 GeV with IceCube DeepCore" paper. Specially in the position of the bf in delta m^2_32.

[Systematics.pdf](https://github.com/icecube/pisa/files/10802503/Systematics.pdf)

Thanks
Roberto

**Comment by philippeller** [comment]
Hi, are you using the public dataset? If yes, then please note that the systematics treatment is a simplified version of what is used in the paper you cite, and the dataset is also slightly newer. So we do not expect 100% identical results.
Your plot suggests that the results are very well compatible i think.

**Comment by ggarg07** [comment]
so, can we mark this issue as resolved and close it?

**Comment by thehrh** [comment]
Let's close given the explanation above and the lack of any follow up.
