### ISSUE TITLE
missing: example/documentation for plotting simple distributions

### ISSUE THREAD

**Issue by blotsd** [icecube/pisa#750]
All of the examples and documentation seem to focus on producing analysis-level histograms, specifically in energy and coszenith. 
I could not find an example showing how to simply get event-wise information from the output of a DistributionMaker. It would be very useful to have some examples where you can get an array of events and their weights, even without histogram stages applied.

**Comment by JKrishnamoorthi** [comment]
Hi, I have raised a pull request for this issue. It would be great if you could review the pull request. Thanks.
