### ISSUE TITLE
Is it still necessary to check pull request for PISA for deprecated Python 3.7 environment?

### ISSUE THREAD

**Issue by anilak41** [icecube/pisa#751]
I have modified `Prob3` in PISA to incorporate neutrino decay. I have included the new functions in the `numba_osc unit test`.  The modification of the `numba_osc` unit test has resulted in some new reference `pkl` files. Since these `pkl` files are produced by current Python (3.10). I have checked that the `numba_osc` unit test is running fine on single and double precision on the local machine (cobalt).

[https://github.com/icecube/pisa/pull/748](https://github.com/icecube/pisa/pull/748
)

While merging my commits to icecube/pisa, it performs checks using Python 3.7 and 3.10. Since the newly produced `pkl` files are not being recognized by Python 3.7, this aborts the check and results in the failure of the merger.  The double precision check on Python 3.10 was successful, and it was checking for the single precision but the failure of Python 3.7 has aborted to test for Python 3.10 also. 

I remember that the current PISA installation dependencies show that at least Python 3.8 is needed, so I can't install PISA with Python 3.7 and can't attempt to reproduce those pkl files with Python 3.7. 

 So, is it still necessary to perform these tests in Python 3.7?

**Comment by atrettin** [comment]
This sounds indeed like we should update the tests, and I don't see anything that would speak against that. A small change in the GitHub CI workflow should do the trick.

**Comment by anilak41** [comment]
Updated the workflow to check for Python 3.8 and 3.10. Now the PR checks are working fine. 

https://github.com/icecube/pisa/pull/752
