### ISSUE TITLE
Broken/missing documentation of analysis

### ISSUE THREAD

**Issue by LeanderFischer** [icecube/pisa#758]
The notebook in [the analysis readme is missing](https://github.com/icecube/pisa/blob/master/pisa/analysis/README.md). A working notebook and/or at least some sentences on how this should be used are needed.

**Comment by atrettin** [comment]
The README should refer to the documentation that is generated from the docstring: https://user-web.icecube.wisc.edu/~peller/pisa_docs/pisa.analysis.html#pisa.analysis.analysis.BasicAnalysis

**Comment by ggarg07** [comment]
Hii @LeanderFischer.....so are you expecting a notebook to show how to use functions from analysis.py or something else? Can you please explicitly let me know?

**Comment by thehrh** [comment]
Close due to https://github.com/icecube/pisa/pull/781
