### ISSUE TITLE
Variable binning options

### ISSUE THREAD

**Issue by JanWeldert** [icecube/pisa#808]
When defining a multidimensional binning we combine one dimensional binnings in a homogeneous grid. So if we for example bin our data in energy, coszen, and PID, we have to use the same energy and coszen binning for all PID bins. It was requested multiple times now to make this more flexible.
A current hack is to use the detectors class to define different "detectors", one per PID bin (to use the example from before), and choose different energy and coszen binning for each of them. Note that for each detector you have to remove all events that don't fall in the respective PID bin.

**Comment by LeanderFischer** [comment]
Potential duplicate/overlap with #108, #158, #248, and #284.

**Comment by JanWeldert** [comment]
Right, #108 has the same idea. The others are mainly talking about making PID a binning dimension, which was already done. Might be possible to close some of them.

**Comment by JanWeldert** [comment]
Both ask for the option to have variable binning options, so we can close this one in favor of #108

**Comment by JanWeldert** [comment]
Use #108 instead
