### ISSUE TITLE
pipeline.py: create dummy inputs if pipeline begins with an input stage?

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#81]
Normally, one would run flux -> osc -> etc. However, it's possible one would want to test osc -> etc. As of now, "dummy" inputs are only generated in the case that the user specifies `--only-stage`. Is it a good idea to accommodate the above scenario, or might that lead to the user running an invalid pipeline? Or should `--dummy-inputs` be another argument to pipeline.py script so that the user must explicitly choose that behavior, and then create these whether or not `--only-stage` is specified? Note that `--only-stage` for an inputs-stage will require the generation of dummy inputs, until such time as we can get inputs from a file (another TODO!).

**Comment by LeanderFischer** [comment]
I don't think this case is really needed to be covered..
