### ISSUE TITLE
List of console scripts (entry points) in setup.py needs updating

### ISSUE THREAD

**Issue by thehrh** [icecube/pisa#810]
See https://github.com/icecube/pisa/blob/a752eaf0f7d75c3d002d3c8ccde4a100ca1bf594/setup.py#L311 and https://setuptools.pypa.io/en/latest/userguide/entry_point.html.

Console scripts that are non-existent (test by running each command) and should be removed:
* `pisa-analysis`
* `pisa-postproc`
* `pisa-fit_discrete_sys` and `pisa-fit_discrete_sys_nd`
* `pisa-make_asymmetry_plots`
* `pisa-make_systematic_variation_plots`
* `pisa-make_toy_events`
* `pisa-profile_scan`
* `pisa-scan_allsyst`

Working scripts for which entry points are missing (possibly incomplete):
* `scripts/create_barr_sys_tables_mceq.py`
* `pisa_tests/test_Detectors_class.py`
* `pisa_tests/test_covariance.py`
* `pisa_tests/test_kde_stage.py`

**Comment by JanWeldert** [comment]
We can delete pisa_tests/test_Detectors_class.py, it just duplicates code from https://github.com/icecube/pisa/blob/master/pisa/core/detectors.py#L346
