### ISSUE TITLE
Events class should read icetray-produced HDF5 files directly

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#86]
We should eliminate the need for an intermediate HDF5 format. I like the PISA HDF5 file format for its conciseness, but it requires an extra processing step and hence another script, and it'd be better for the user to be able to just convert I3 -> HDF5 in icetray and be done with file formats.

**Comment by LeanderFischer** [comment]
I don't think this makes any sense, we want some pre-processing/combining of icectray i3/hdf5 files before feeding them into an analysis, it is an extra step, but I don't see the point of getting rid of it, causing more problems than solving any..
