### ISSUE TITLE
Physics unit tests for all stages

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#89]
pull request #51 introduced physics unit tests to verify basic / hist services for each stage implemented in PISA 2 as well matched output of PISA 2's stages. We need the same for _all_ stages / services implemented beyond those. And probably in some cases we'll want the baseline to be output of PISA 3 (or something else entirely), where there is no corresponding stage in PISA 2.

**Comment by LeanderFischer** [comment]
I don't know what this PISA 2/3 stuff refers to, but we live in PISA 4 era now, so I assume this is not relevant anymore..
