### ISSUE TITLE
unit tests: test that each stage works with arbitary binning

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#90]
Binning orders I can think of that the user might specify (some are ok if they don't work in certain stages, if there's a good reason why that binning choice should fail):

```
e
cz
az
e, cz
cz, e
e, cz, az
e, az, cz
cz, e, az
cz, az, e
az, e, cz
az, cz, e
```

and eventually we'll have a pid binning as well...

**Comment by LeanderFischer** [comment]
I think our setup doesn't really allow for arbitrary binnings anyway, so not sure checking that it works for every stage makes sense at all :see_no_evil:
